name: Build and Deploy to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Ensure SPA fallback
        # Make GitHub Pages serve index.html for unknown routes
        run: |
          if [ -d "dist" ] && [ -f "dist/index.html" ]; then
            cp -f dist/index.html dist/404.html || true
          else
            echo "dist/index.html not found; skipping SPA fallback"
          fi

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v1
